### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by edgiru** [pconnor88/instagram-profile-widget#3]
![default](https://cloud.githubusercontent.com/assets/4624056/21681090/a61fc1ea-d35e-11e6-8ad2-1d4a150fe124.PNG)

**Comment by kamaleao** [comment]
not working

**Comment by edgiru** [comment]
DUE TO INSTAGRAM UPDATING THEIR API ON THE 01/06/2016, THIS PLUGIN CAN NO LONGER USE THE CLIENT ID TOKEN TO ACCESS THE INSTAGRAM API, SO WILL NOT DISPLAY ANY PROFILE INFORMATION OR IMAGES
